
name: CI/CD for auth-service

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  auth-service:
    if: |
      contains(github.event.head_commit.message, 'auth-service') ||
      contains(toJSON(github.event.commits.*.message), 'auth-service') ||
      contains(github.event.pull_request.title, 'auth-service')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./auth-service
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.20.0'
      - name: Install Dependencies
        run: npm ci 
      - name: Deploy to render 
        if: success()
        run: curl -X POST ${{ secrets.RENDER_AUTH_SERVICE_DEPLOY_HOOK }}